### PR TITLE
GM: Add params to dataview.data endpoint

### PR DESCRIPTION
**Pull request by geoffreymuchai**
Required by https://github.com/onaio/zebra/issues/4216

### CODE REVIEW

**Comment by pld** [comment]
this diff looks pretty conflicty

**Comment by geoffreymuchai** [comment]
@pld... in what sense? It will be merged into the DFID Syria branch

**Comment by pld** [comment]
in that it "has conflicts that must be resolved"

**Comment by geoffreymuchai** [comment]
@pld resolved

**Pull request merged**
