### PR TITLE
Add rest-services endpoint support

### LINKED ISSUE #77: Add support for rest services endpoint
https://ona.io/static/docs/restservices.html

### PR DESCRIPTION
**Pull request by okal**
Closes #77

### CODE REVIEW

**Comment by pld** [comment]
Looks good, but it needs tests

**Comment by okal** [comment]
I thought so too, but all the functions do is call `parse-http`. Is that worth testing?

**Comment by okal** [comment]
i.e. they have no real internal logic.

**Comment by okal** [comment]
Writing tests to check the params sent to parse-http.

**Comment by pld** [comment]
I think it's worthwhile to test that the create function calls parse http with the correct params

**Pull request merged**
