### PR TITLE
Remove : from default argument values using :or construct

### PR DESCRIPTION
**Pull request by FrankApiyo**
Fixes: https://github.com/onaio/milia/issues/300

### CODE REVIEW

**Review by pld — APPROVED** [review]

**Review by JohnMwashuma — COMMENTED** [review]
Should we add tests that will fail when the full colon was present?

**Comment by FrankApiyo** [comment]
> Should we add tests that will fail when the full colon was present?

We could add tests for the functions changed in this PR. 

A better approach would be to use a linter that will always catch any error like this anywhere it happens. Seems clj-kondo doesn't check for this kind of error buy they say they can easily add it https://github.com/clj-kondo/clj-kondo/issues/1242#issuecomment-809458094

**Comment by JohnMwashuma** [comment]
> > Should we add tests that will fail when the full colon was present?
> 
> A better approach, IMO, would be to use a linter that will always catch any error like this anywhere it happens. Seems clj-kondo doesn't check for this kind of error buy they say they can easily add it [clj-kondo/clj-kondo#1242 (comment)](https://github.com/clj-kondo/clj-kondo/issues/1242#issuecomment-809458094)

At the moment we are using [eastwood](https://github.com/onaio/milia/blob/c68b612bd640aa2499e4ac2f907a7ef793d0820a/project.clj#L37) will this mean switching to clj-kondo?

**Comment by FrankApiyo** [comment]
not necessarily, I think they can complement each other. I personally use clj-kondo locally and I totally like it and would like to add it to our repositories here soon

**Comment by FrankApiyo** [comment]
I was able to get a PR that adds support for this in clj-kondo 🛩️ 

https://github.com/clj-kondo/clj-kondo/pull/1245

**Pull request merged**
